### ISSUE TITLE
Is it possible to serialize with serde?

### ISSUE THREAD

**Issue by Bastczuak** [jojolepro/planck_ecs#2]
Hello,

I want to use your ECS with WASM. But I struggle to return the state of the world back to Javascript after I ran a dispatcher. 

let's take this little example. `dispatch` is exposed via `wasm_bindgen` to Javascript. Javascript calls the function, the `dispatch` of the `world` is triggered and I want to return the result.
```rs
  pub fn dispatch(&mut self) -> JsValue {
    let run = (|animals: &mut Components<Animal>, points: &mut Components<na::Point2<f32>>| {
      for (_, point) in join!(&animals && &points) {
       //...
      }
      Ok(())
    }).system();
    let mut dispatch = DispatcherBuilder::new().add_system(run).build(&mut self.world);
    dispatch.run_seq(&self.world).unwrap();

   // now I want to return all entities which have animal and points as json to the browser
  }
```
Is it possible to use serde with your ECS out of the box? If so can you provide me an example.

Thanks in advance!

**Comment by AnneKitsune** [comment]
Hi!

We have a feature called "ser" here: https://github.com/jojolepro/planck_ecs/blob/master/Cargo.toml#L23

To enable it, you can use
```
planck_ecs = { version = "*", features = ["ser"] }
```
This will allow you to serialize `Entity`  (https://github.com/jojolepro/entity_component/blob/master/src/entity.rs#L8)

From here, you need to ensure that your component types are serializable (Animal and Point2<f32>).

Then, you can do something like this:
```rust
let cloned_data = join!(&self.world.get::<Entities>().unwrap(),
    &self.world.get::<Components<Animal>>().unwrap(),
    &self.world.get::<Point2<f32>>().unwrap(),
    ).cloned().collect::<Vec<_>>();
```
This will give you a `Vec<(Entity, Animal, Point2<f32>)>`, which you can serialize using json:
```rust
serde_json::to_pretty(&cloned_data);
```

There's probably also a way to do that without cloning the data (the cloned() function in the example).

I hope this helps :hearts:

**Comment by Bastczuak** [comment]
@jojolepro My compiler tells me the error ` the trait bound Entity: Serialize is not satisfied` with the `ser` feature enabled. 

Then using `.cloned()` was also producing errors `method cannot be called on Cloned<Zip<ComponentIterator<'_, Animal>, ComponentIterator<'_, Point<f32, 2_usize>>>> due to unsatisfied trait bounds`. So I just called collect(). And using commas and `self.world` in the macro also didn't work for me. So add the end I have something like this.

```rs
    let animals = self.world.get::<Components<Animal>>().unwrap();
    let positions = self.world.get::<Components<na::Point2<f32>>>().unwrap();

    let cloned_data = join!(&animals && &positions).collect::<Vec<_>>();

    JsValue::from_serde(&cloned_data).unwrap()
```
https://github.com/Bastczuak/learn-to-fly/blob/5f8e899e58c89d61b81e462edcc3a0306aa44f4c/src/lib.rs#L79-L84

**Comment by AnneKitsune** [comment]
yeah I was writing pseudo-code which I didn't test. ^u^
You are right about Entity: Serialize, I did a mistake in the Cargo.toml file of planck_ecs. I'll fix this right now and push a patch update.

I'm happy that this is working for you! Let me know if you need more help with something :)

Also, would you like to write an example showcasing serialization in planck_ecs/examples ?

**Comment by Bastczuak** [comment]
Yeah I can do that.

**Comment by AnneKitsune** [comment]
:hearts:
